---
abstract: 'Delegate session storage to an'
author:
  - 'Yuval Kogman, C<nothingmuch@woobling.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::use::ok: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Catalyst::Plugin::Session::Store::Delegate
name: Catalyst-Plugin-Session-Store-Delegate
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Plugin::Session: 0.12
  Class::Accessor::Fast: 0
  MRO::Compat: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
