--- #YAML:1.0
name:               Catalyst-Plugin-Session-Store-Delegate
version:            0.03
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Plugin::Session:  0.12
    Class::Accessor::Fast:  0
    MRO::Compat:          0
    Test::More:           0
    Test::use::ok:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
